version: '3.8'  # Definindo a versão do Compose

services:
  mysql:
    image: mysql:latest  # Usando a imagem mais recente do MySQL
    container_name: mysql-container  # Nome do container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Senha do usuário root
      MYSQL_DATABASE: mydatabase  # Nome do banco de dados a ser criado (opcional)
    ports:
      - "3306:3306"  # Mapeando a porta do MySQL (para acesso externo)
    volumes:
      - mysql-data:/var/lib/mysql  # Persistência de dados usando volumes
    restart: always  # Reinicia o container automaticamente se falhar

volumes:
  mysql-data:  # Definindo um volume para persistir os dados do MySQL
